language: python
stages:
- quality-assurance
- deploy
cache: pip
jobs:
  include:
  - stage: quality-assurance
    python: '3.6'
    install: pip install flake8
    script: flake8

  - stage: quality-assurance
    python: '3.6'
    before_install:
    - pip install pytest==4.3.0 pytest-cov
    install:
    - python setup.py install
    script:
    - pytest --cov dropblock --cov-report term-missing -v tests/
